# Translations template for networking-l2gw.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the networking-l2gw
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: networking-l2gw 2015.1.2.dev61\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-11-30 00:56-0800\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.1.1\n"

#: networking_l2gw/db/l2gateway/db_query.py:77
msgid "Cannot create resource for another tenant"
msgstr ""

#: networking_l2gw/db/l2gateway/l2gateway_db.py:371
#, python-format
msgid "Cannot %s resource for non admin tenant"
msgstr ""

#: networking_l2gw/l2gatewayclient/l2gw_client_ext/_l2_gateway.py:66
msgid ""
"Device name and Interface-names of l2gateway. INTERFACE-DETAILS is of "
"form \"<interface_name1>;[<interface_name2>][|<seg_id1>[#<seg_id2>]]\" "
"(--device option can be repeated)"
msgstr ""

#: networking_l2gw/l2gatewayclient/l2gw_client_ext/_l2_gateway.py:111
#: networking_l2gw/l2gatewayclient/l2gw_client_ext/_l2_gateway.py:151
#: networking_l2gw/l2gatewayclient/l2gw_client_ext/_l2_gateway_connection.py:49
msgid "Descriptive name for logical gateway."
msgstr ""

#: networking_l2gw/l2gatewayclient/l2gw_client_ext/_l2_gateway_connection.py:52
msgid "Network name or uuid."
msgstr ""

#: networking_l2gw/l2gatewayclient/l2gw_client_ext/_l2_gateway_connection.py:56
msgid ""
"default segmentation-id that willbe applied to the interfaces for "
"whichsegmentation id was not specifiedin l2-gateway-create command."
msgstr ""

#: networking_l2gw/services/l2gateway/exceptions.py:23
#, python-format
msgid ""
"L2 Gateway '%(gateway_id)s' still has active mappings with one or more "
"neutron networks."
msgstr ""

#: networking_l2gw/services/l2gateway/exceptions.py:28
#, python-format
msgid "L2 Gateway %(gateway_id)s could not be found"
msgstr ""

#: networking_l2gw/services/l2gateway/exceptions.py:32
#, python-format
msgid ""
"L2 Gateway Device '%(device_id)s' is still used by one or more network "
"gateways."
msgstr ""

#: networking_l2gw/services/l2gateway/exceptions.py:37
#, python-format
msgid "L2 Gateway Device %(device_id)s could not be found."
msgstr ""

#: networking_l2gw/services/l2gateway/exceptions.py:41
#, python-format
msgid "L2 Gateway Device %(device_name)s could not be found."
msgstr ""

#: networking_l2gw/services/l2gateway/exceptions.py:45
#, python-format
msgid ""
"Port '%(port_id)s' is owned by '%(device_owner)s' and therefore cannot be"
" deleted directly via the port API."
msgstr ""

#: networking_l2gw/services/l2gateway/exceptions.py:50
#, python-format
msgid ""
"The specified mapping '%(mapping)s' exists on network gateway "
"'%(gateway_id)s'."
msgstr ""

#: networking_l2gw/services/l2gateway/exceptions.py:55
#, python-format
msgid ""
"Multiple network connections found on '%(gateway_id)s' with provided "
"criteria."
msgstr ""

#: networking_l2gw/services/l2gateway/exceptions.py:60
#, python-format
msgid "L2 Gateway interface '%(interface_id)s' not found."
msgstr ""

#: networking_l2gw/services/l2gateway/exceptions.py:64
#, python-format
msgid ""
"Physical Port '%(int_name)s' in Physical switch '%(device_name)s' "
"port_fault_status is '%(fault_status)s'"
msgstr ""

#: networking_l2gw/services/l2gateway/exceptions.py:69
#, python-format
msgid ""
"Physical Switch '%(device_name)s' switch_fault_status is "
"'%(fault_status)s'"
msgstr ""

#: networking_l2gw/services/l2gateway/exceptions.py:74
#, python-format
msgid "The connection %(id)s not found on the l2 gateway"
msgstr ""

#: networking_l2gw/services/l2gateway/exceptions.py:78
#, python-format
msgid "The segmentation id not found on gateway '%(gateway_id)s'"
msgstr ""

#: networking_l2gw/services/l2gateway/exceptions.py:83
#, python-format
msgid "Multiple segments found for the network  '%(network_id)s'"
msgstr ""

#: networking_l2gw/services/l2gateway/exceptions.py:87
msgid "L2 Gateway Interface required"
msgstr ""

#: networking_l2gw/services/l2gateway/exceptions.py:91
#, python-format
msgid ""
"The segmentation id is already specified in gateway interface "
"'%(interface_id)s'."
msgstr ""

#: networking_l2gw/services/l2gateway/exceptions.py:96
msgid "L2 gateway segmentation id must be consistent for all the interfaces"
msgstr ""

#: networking_l2gw/services/l2gateway/exceptions.py:101
#: networking_l2gw/services/l2gateway/exceptions.py:105
#, python-format
msgid "%(message)s"
msgstr ""

#: networking_l2gw/services/l2gateway/plugin.py:113
msgid "Communication error with the L2 gateway agent"
msgstr ""

#: networking_l2gw/services/l2gateway/plugin.py:472
#: networking_l2gw/services/l2gateway/plugin.py:701
msgid "The PHYSICAL SWITCH data not found in the server"
msgstr ""

#: networking_l2gw/services/l2gateway/plugin.py:484
msgid "The LOGICAL SWITCH data not found in the server"
msgstr ""

#: networking_l2gw/services/l2gateway/plugin.py:492
msgid "The PHYSICAL PORT data not found in the server"
msgstr ""

#: networking_l2gw/services/l2gateway/plugin.py:518
#, python-format
msgid "Duplicate segmentation ID for the interface name=%(name)s uuid=%(uuid)s"
msgstr ""

#: networking_l2gw/services/l2gateway/common/config.py:26
msgid "OVSDB server name:host/IP:port"
msgstr ""

#: networking_l2gw/services/l2gateway/common/config.py:29
msgid "L2 gateway agent private key"
msgstr ""

#: networking_l2gw/services/l2gateway/common/config.py:32
msgid "L2 gateway agent public certificate"
msgstr ""

#: networking_l2gw/services/l2gateway/common/config.py:35
msgid "Trusted issuer CA cert"
msgstr ""

#: networking_l2gw/services/l2gateway/common/config.py:38
msgid "Seconds between periodic task runs"
msgstr ""

#: networking_l2gw/services/l2gateway/common/config.py:41
msgid "Set to True if ovsdb Manager manages the client"
msgstr ""

#: networking_l2gw/services/l2gateway/common/config.py:44
msgid "Maximum number of retries to open a socket with the OVSDB server"
msgstr ""

#: networking_l2gw/services/l2gateway/common/config.py:51
msgid "default_interface_name of the l2 gateway"
msgstr ""

#: networking_l2gw/services/l2gateway/common/config.py:54
msgid "default_device_name of the l2 gateway"
msgstr ""

#: networking_l2gw/services/l2gateway/common/config.py:57
msgid "Number of l2 gateways allowed per tenant, -1 for unlimited"
msgstr ""

#: networking_l2gw/services/l2gateway/common/config.py:61
msgid ""
"Periodic interval at which the plugin checks for the monitoring L2 "
"gateway agent"
msgstr ""

#: networking_l2gw/services/l2gateway/common/config.py:66
msgid ""
"L2 gateway plugin callback class where theRPCs from the agent are going "
"to get invoked"
msgstr ""

#: networking_l2gw/services/l2gateway/common/l2gw_validators.py:31
msgid "Cannot create a gateway with an empty device list"
msgstr ""

#: networking_l2gw/services/l2gateway/common/l2gw_validators.py:38
msgid "Cannot create a gateway with an empty device_name"
msgstr ""

#: networking_l2gw/services/l2gateway/common/l2gw_validators.py:41
msgid "Cannot create a gateway with an empty interfaces"
msgstr ""

#: networking_l2gw/services/l2gateway/common/l2gw_validators.py:46
msgid "Cannot create a gateway with an emptyinterface name"
msgstr ""

#: networking_l2gw/services/l2gateway/common/l2gw_validators.py:52
msgid "segmentation_id type should be of list type "
msgstr ""

#: networking_l2gw/services/l2gateway/common/l2gw_validators.py:55
msgid "segmentation_id_list should not be empty"
msgstr ""

#: networking_l2gw/services/l2gateway/common/l2gw_validators.py:62
#, python-format
msgid "%s: provided data are not iterable"
msgstr ""

#: networking_l2gw/services/l2gateway/common/l2gw_validators.py:71
msgid ""
"default segmentation_id should not be provided when segmentation_id is "
"assigned during l2gateway creation"
msgstr ""

#: networking_l2gw/services/l2gateway/common/l2gw_validators.py:80
msgid "Segmentation id must be specified in createl2gateway connections"
msgstr ""

#: networking_l2gw/services/l2gateway/common/l2gw_validators.py:85
msgid ""
"A valid network identifier must be specified when connecting a network to"
" a network gateway. Unable to complete operation"
msgstr ""

#: networking_l2gw/services/l2gateway/common/l2gw_validators.py:91
#, python-format
msgid ""
"Invalid keys found among the ones provided in request : "
"%(connection_attrs)s."
msgstr ""

#: networking_l2gw/services/l2gateway/common/l2gw_validators.py:101
msgid "Segmentation id must be a valid integer"
msgstr ""

#: networking_l2gw/services/l2gateway/common/l2gw_validators.py:104
msgid "Segmentation id is out of range"
msgstr ""

